import { Badge } from '@/types';

// 50 badges: 15 easy, 25 medium, 10 hard
export const ALL_BADGES: Badge[] = [
  // ═══════════════════════════════════════════
  //  EASY (15) — Quick wins to hook new users
  // ═══════════════════════════════════════════

  {
    id: 'first-watch',
    name: 'First Watch',
    description: 'Mark your first title as watched',
    icon: 'HiPlay',
    difficulty: 'easy',
    category: 'watching',
    criteria: { type: 'total_watched', threshold: 1 },
    color: '#10b981',
  },
  {
    id: 'getting-started',
    name: 'Getting Started',
    description: 'Add 3 titles to your watchlist',
    icon: 'HiBookmark',
    difficulty: 'easy',
    category: 'watching',
    criteria: { type: 'total_watchlist', threshold: 3 },
    color: '#6366f1',
  },
  {
    id: 'first-rating',
    name: 'Critic Debut',
    description: 'Rate your first title',
    icon: 'HiStar',
    difficulty: 'easy',
    category: 'rating',
    criteria: { type: 'total_rated', threshold: 1 },
    color: '#ffd700',
  },
  {
    id: 'movie-starter',
    name: 'Movie Night',
    description: 'Watch 3 movies',
    icon: 'HiFilm',
    difficulty: 'easy',
    category: 'watching',
    criteria: { type: 'movies_watched', threshold: 3 },
    color: '#ef4444',
  },
  {
    id: 'tv-starter',
    name: 'Couch Potato',
    description: 'Watch 2 TV series',
    icon: 'HiTv',
    difficulty: 'easy',
    category: 'watching',
    criteria: { type: 'tv_watched', threshold: 2 },
    color: '#3b82f6',
  },
  {
    id: 'anime-starter',
    name: 'Weeb Initiate',
    description: 'Watch your first anime',
    icon: 'HiSparkles',
    difficulty: 'easy',
    category: 'watching',
    criteria: { type: 'anime_watched', threshold: 1 },
    color: '#ec4899',
  },
  {
    id: 'five-watched',
    name: 'High Five',
    description: 'Watch 5 titles',
    icon: 'HiHandRaised',
    difficulty: 'easy',
    category: 'watching',
    criteria: { type: 'total_watched', threshold: 5 },
    color: '#f59e0b',
  },
  {
    id: 'recommender',
    name: 'Good Friend',
    description: 'Send your first recommendation',
    icon: 'HiHeart',
    difficulty: 'easy',
    category: 'social',
    criteria: { type: 'recommendations_sent', threshold: 1 },
    color: '#ec4899',
  },
  {
    id: 'first-collection',
    name: 'Curator',
    description: 'Create your first collection',
    icon: 'HiRectangleStack',
    difficulty: 'easy',
    category: 'collection',
    criteria: { type: 'collections_created', threshold: 1 },
    color: '#8b5cf6',
  },
  {
    id: 'perfect-score',
    name: 'Masterpiece Found',
    description: 'Give a title a perfect 10/10 rating',
    icon: 'HiTrophy',
    difficulty: 'easy',
    category: 'rating',
    criteria: { type: 'perfect_rating', threshold: 10 },
    color: '#ffd700',
  },
  {
    id: 'list-builder',
    name: 'List Builder',
    description: 'Have 5 items in your list',
    icon: 'HiQueueList',
    difficulty: 'easy',
    category: 'watching',
    criteria: { type: 'total_in_list', threshold: 5 },
    color: '#06b6d4',
  },
  {
    id: 'two-recs',
    name: 'Spreading the Word',
    description: 'Send 2 recommendations',
    icon: 'HiMegaphone',
    difficulty: 'easy',
    category: 'social',
    criteria: { type: 'recommendations_sent', threshold: 2 },
    color: '#f97316',
  },
  {
    id: 'multi-watcher',
    name: 'Multitasker',
    description: 'Have 2 titles in "Watching" status at once',
    icon: 'HiArrowsPointingOut',
    difficulty: 'easy',
    category: 'watching',
    criteria: { type: 'watching_count', threshold: 2 },
    color: '#14b8a6',
  },
  {
    id: 'three-ratings',
    name: 'Opinionated',
    description: 'Rate 3 titles',
    icon: 'HiChatBubbleLeft',
    difficulty: 'easy',
    category: 'rating',
    criteria: { type: 'total_rated', threshold: 3 },
    color: '#a855f7',
  },
  {
    id: 'five-movies',
    name: 'Film Buff',
    description: 'Watch 5 movies',
    icon: 'HiFilm',
    difficulty: 'easy',
    category: 'watching',
    criteria: { type: 'movies_watched', threshold: 5 },
    color: '#e11d48',
  },

  // ═══════════════════════════════════════════
  //  MEDIUM (25) — Core engagement badges
  // ═══════════════════════════════════════════

  {
    id: 'ten-watched',
    name: 'Double Digits',
    description: 'Watch 10 titles',
    icon: 'HiFire',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'total_watched', threshold: 10 },
    color: '#ef4444',
  },
  {
    id: 'twenty-watched',
    name: 'Binge Machine',
    description: 'Watch 20 titles',
    icon: 'HiBolt',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'total_watched', threshold: 20 },
    color: '#f59e0b',
  },
  {
    id: 'ten-movies',
    name: 'Cinephile',
    description: 'Watch 10 movies',
    icon: 'HiFilm',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'movies_watched', threshold: 10 },
    color: '#dc2626',
  },
  {
    id: 'five-tv',
    name: 'Series Addict',
    description: 'Watch 5 TV series',
    icon: 'HiTv',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'tv_watched', threshold: 5 },
    color: '#2563eb',
  },
  {
    id: 'five-anime',
    name: 'Otaku Rising',
    description: 'Watch 5 anime',
    icon: 'HiSparkles',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'anime_watched', threshold: 5 },
    color: '#d946ef',
  },
  {
    id: 'all-types',
    name: 'Renaissance Viewer',
    description: 'Watch at least one movie, TV show, and anime',
    icon: 'HiGlobeAlt',
    difficulty: 'medium',
    category: 'exploration',
    criteria: { type: 'media_types_watched', threshold: 3 },
    color: '#0ea5e9',
  },
  {
    id: 'ten-ratings',
    name: 'Seasoned Critic',
    description: 'Rate 10 titles',
    icon: 'HiStar',
    difficulty: 'medium',
    category: 'rating',
    criteria: { type: 'total_rated', threshold: 10 },
    color: '#eab308',
  },
  {
    id: 'five-high-ratings',
    name: 'Generous Judge',
    description: 'Give 5 titles a rating of 8 or above',
    icon: 'HiHandThumbUp',
    difficulty: 'medium',
    category: 'rating',
    criteria: { type: 'rated_high', threshold: 5 },
    color: '#22c55e',
  },
  {
    id: 'harsh-critic',
    name: 'Harsh Critic',
    description: 'Give a title 3/10 or below',
    icon: 'HiHandThumbDown',
    difficulty: 'medium',
    category: 'rating',
    criteria: { type: 'low_rating', threshold: 3 },
    color: '#dc2626',
  },
  {
    id: 'five-recs',
    name: 'Influencer',
    description: 'Send 5 recommendations',
    icon: 'HiShare',
    difficulty: 'medium',
    category: 'social',
    criteria: { type: 'recommendations_sent', threshold: 5 },
    color: '#8b5cf6',
  },
  {
    id: 'three-collections',
    name: 'Organized Mind',
    description: 'Create 3 collections',
    icon: 'HiFolderOpen',
    difficulty: 'medium',
    category: 'collection',
    criteria: { type: 'collections_created', threshold: 3 },
    color: '#0d9488',
  },
  {
    id: 'ten-in-collection',
    name: 'Collector',
    description: 'Have 10 items in a single collection',
    icon: 'HiArchiveBox',
    difficulty: 'medium',
    category: 'collection',
    criteria: { type: 'collection_items', threshold: 10 },
    color: '#7c3aed',
  },
  {
    id: 'fifteen-in-list',
    name: 'List Master',
    description: 'Have 15 items in your watchlist',
    icon: 'HiClipboardDocumentList',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'total_in_list', threshold: 15 },
    color: '#0891b2',
  },
  {
    id: 'reviewer',
    name: 'Thoughtful Reviewer',
    description: 'Write reviews for 3 ratings',
    icon: 'HiPencilSquare',
    difficulty: 'medium',
    category: 'rating',
    criteria: { type: 'rated_with_review', threshold: 3 },
    color: '#059669',
  },
  {
    id: 'ten-recs',
    name: 'Tastemaker',
    description: 'Send 10 recommendations',
    icon: 'HiSpeakerWave',
    difficulty: 'medium',
    category: 'social',
    criteria: { type: 'recommendations_sent', threshold: 10 },
    color: '#e11d48',
  },
  {
    id: 'fifteen-watched',
    name: 'Dedicated Viewer',
    description: 'Watch 15 titles',
    icon: 'HiEye',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'total_watched', threshold: 15 },
    color: '#7c3aed',
  },
  {
    id: 'high-standards',
    name: 'High Standards',
    description: 'Have an average rating above 8',
    icon: 'HiAcademicCap',
    difficulty: 'medium',
    category: 'rating',
    criteria: { type: 'avg_rating_above', threshold: 8 },
    color: '#ca8a04',
  },
  {
    id: 'eight-movies',
    name: 'Movie Marathon',
    description: 'Watch 8 movies',
    icon: 'HiFilm',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'movies_watched', threshold: 8 },
    color: '#b91c1c',
  },
  {
    id: 'dropped-one',
    name: 'Know Your Limits',
    description: 'Drop a title you were watching',
    icon: 'HiXCircle',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'dropped_count', threshold: 1 },
    color: '#64748b',
  },
  {
    id: 'three-anime',
    name: 'Anime Explorer',
    description: 'Watch 3 anime',
    icon: 'HiSparkles',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'anime_watched', threshold: 3 },
    color: '#c026d3',
  },
  {
    id: 'five-collections',
    name: 'Archivist',
    description: 'Create 5 collections',
    icon: 'HiSquares2X2',
    difficulty: 'medium',
    category: 'collection',
    criteria: { type: 'collections_created', threshold: 5 },
    color: '#4f46e5',
  },
  {
    id: 'fifteen-movies',
    name: 'Silver Screen Lover',
    description: 'Watch 15 movies',
    icon: 'HiFilm',
    difficulty: 'medium',
    category: 'watching',
    criteria: { type: 'movies_watched', threshold: 15 },
    color: '#9f1239',
  },
  {
    id: 'five-reviews',
    name: 'Wordsmith',
    description: 'Write reviews for 5 ratings',
    icon: 'HiDocumentText',
    difficulty: 'medium',
    category: 'rating',
    criteria: { type: 'rated_with_review', threshold: 5 },
    color: '#0f766e',
  },
  {
    id: 'ten-high-ratings',
    name: 'Positive Vibes',
    description: 'Give 10 titles a rating of 8 or above',
    icon: 'HiHandThumbUp',
    difficulty: 'medium',
    category: 'rating',
    criteria: { type: 'rated_high', threshold: 10 },
    color: '#16a34a',
  },
  {
    id: 'twenty-in-collection',
    name: 'Super Collector',
    description: 'Have 20 items in a single collection',
    icon: 'HiArchiveBox',
    difficulty: 'medium',
    category: 'collection',
    criteria: { type: 'collection_items', threshold: 20 },
    color: '#6d28d9',
  },

  // ═══════════════════════════════════════════
  //  HARD (10) — Long-term dedication
  // ═══════════════════════════════════════════

  {
    id: 'fifty-watched',
    name: 'Half Century',
    description: 'Watch 50 titles',
    icon: 'HiFire',
    difficulty: 'hard',
    category: 'dedication',
    criteria: { type: 'total_watched', threshold: 50 },
    color: '#dc2626',
  },
  {
    id: 'hundred-watched',
    name: 'Centurion',
    description: 'Watch 100 titles',
    icon: 'HiShieldCheck',
    difficulty: 'hard',
    category: 'dedication',
    criteria: { type: 'total_watched', threshold: 100 },
    color: '#fbbf24',
  },
  {
    id: 'thirty-movies',
    name: 'Cinema Legend',
    description: 'Watch 30 movies',
    icon: 'HiFilm',
    difficulty: 'hard',
    category: 'watching',
    criteria: { type: 'movies_watched', threshold: 30 },
    color: '#991b1b',
  },
  {
    id: 'ten-tv',
    name: 'TV Overlord',
    description: 'Watch 10 TV series',
    icon: 'HiTv',
    difficulty: 'hard',
    category: 'watching',
    criteria: { type: 'tv_watched', threshold: 10 },
    color: '#1d4ed8',
  },
  {
    id: 'ten-anime',
    name: 'True Otaku',
    description: 'Watch 10 anime',
    icon: 'HiSparkles',
    difficulty: 'hard',
    category: 'watching',
    criteria: { type: 'anime_watched', threshold: 10 },
    color: '#a21caf',
  },
  {
    id: 'twenty-ratings',
    name: 'Master Critic',
    description: 'Rate 20 titles',
    icon: 'HiStar',
    difficulty: 'hard',
    category: 'rating',
    criteria: { type: 'total_rated', threshold: 20 },
    color: '#b45309',
  },
  {
    id: 'twenty-recs',
    name: 'Community Pillar',
    description: 'Send 20 recommendations',
    icon: 'HiUserGroup',
    difficulty: 'hard',
    category: 'social',
    criteria: { type: 'recommendations_sent', threshold: 20 },
    color: '#be185d',
  },
  {
    id: 'ten-collections',
    name: 'Grand Curator',
    description: 'Create 10 collections',
    icon: 'HiBuildingLibrary',
    difficulty: 'hard',
    category: 'collection',
    criteria: { type: 'collections_created', threshold: 10 },
    color: '#4338ca',
  },
  {
    id: 'thirty-in-collection',
    name: 'Ultimate Collector',
    description: 'Have 30 items in a single collection',
    icon: 'HiArchiveBox',
    difficulty: 'hard',
    category: 'collection',
    criteria: { type: 'collection_items', threshold: 30 },
    color: '#5b21b6',
  },
  {
    id: 'ten-reviews',
    name: 'Elite Reviewer',
    description: 'Write reviews for 10 ratings',
    icon: 'HiPencilSquare',
    difficulty: 'hard',
    category: 'rating',
    criteria: { type: 'rated_with_review', threshold: 10 },
    color: '#047857',
  },
];

export const BADGE_MAP = Object.fromEntries(ALL_BADGES.map((b) => [b.id, b]));

export const DIFFICULTY_CONFIG = {
  easy: { label: 'Easy', color: '#10b981', bg: 'rgba(16, 185, 129, 0.1)', border: 'rgba(16, 185, 129, 0.3)' },
  medium: { label: 'Medium', color: '#f59e0b', bg: 'rgba(245, 158, 11, 0.1)', border: 'rgba(245, 158, 11, 0.3)' },
  hard: { label: 'Hard', color: '#ef4444', bg: 'rgba(239, 68, 68, 0.1)', border: 'rgba(239, 68, 68, 0.3)' },
};

export const CATEGORY_CONFIG = {
  watching: { label: 'Watching', color: '#3b82f6' },
  rating: { label: 'Rating', color: '#ffd700' },
  social: { label: 'Social', color: '#ec4899' },
  collection: { label: 'Collections', color: '#8b5cf6' },
  exploration: { label: 'Exploration', color: '#06b6d4' },
  dedication: { label: 'Dedication', color: '#ef4444' },
};
